amurphy10=EBANK
amurphy0=EBANK
bneumann3=OTHER
bneumann4=OTHER
douano=HY2
douano1=HY2
koconnor4=AUTO
koconnor6=AUTO
mkrys1=BANKFIN
mkrys2=BANKFIN
mhendrickson=EM
mhendrickson1=EM
rchampagne=HIGHYLD
rchampagne1=HIGHYLD
mbarone1=TMT
gilbride1=MTN
hart1=ETF
jobrien01=BABS
jchampagne=NWEST
