NA=bneumann3
#
EBANK=amurphy10
MBS=amurphy10
AT1=amurphy10
OTHER=bneumann3
HY2=douano
TMT=mbarone1
AUTO=koconnor4
BANKFIN=mkrys1
EM=mhendrickson
HYBRIDS=rchampagne
HIGHYLD=rchampagne
MTN=jmuoio
FRONT=jmuoio
ETF=hart1
BABS=jobrien01
