amurphy10=EBANK
amurphy0=EBANK
bneumann3=OTHER
bneumann4=OTHER
douano=HY2
douano1=HY2
jmorris9=TMT
jmorris0=TMT
koconnor4=AUTO
koconnor6=AUTO
mkrys1=BANKFIN
mkrys2=BANKFIN
mhendrickson=EM
mhendrickson1=EM
rchampagne=HIGHYLD
rchampagne1=HIGHYLD
gilbride1=MTN
hart1=ETF
#test
pvalentien=TMT
jjiangdlr=BANKFIN
jjiangdrfq=EM